SecondHand/models.py
from django.db import models


class UserInfo(models.Model):
    """ 用户表"""
    username = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=64)
    create_time = models.DateField(verbose_name="创建时间", auto_now_add=True)

    usertype_choices = (
        (1, "用户"),
        (2, "管理员"),
    )
    usertype = models.SmallIntegerField(verbose_name="用户身份", choices=usertype_choices)

    status_choices = (
        (1, "注销"),
        (2, "正常"),
        (3, "冻结"),
    )
    statustype = models.SmallIntegerField(verbose_name="用户状态", choices=status_choices, default=2)

    def __str__(self):
        return self.username


class ItemInfo(models.Model):
    """ 二手物品表"""

    seller = models.ForeignKey(verbose_name="卖家ID", to="UserInfo", to_field="id", on_delete=models.CASCADE)
    item_name = models.CharField(verbose_name="物品名称", max_length=32)
    item_category = models.ForeignKey(verbose_name="物品种类", to="ItemCategory", to_field="id",
                                      on_delete=models.CASCADE)
    purchase_time = models.DateField(verbose_name="购买时间")

    condition_choices = (
        (1, "九成新"),
        (2, "七成新"),
        (3, "五成新"),
        (4, "其他"),
    )

    item_condition = models.SmallIntegerField(verbose_name="新旧程度", choices=condition_choices)

    price = models.DecimalField(verbose_name='价格', max_digits=10, decimal_places=2)

    location = models.CharField(verbose_name="交易位置", max_length=32)

    publish_time = models.DateField(verbose_name='发布时间', auto_now_add=True)

    item_img = models.FileField(verbose_name="物品图片", max_length=1024, upload_to='item/')

    item_description = models.TextField(verbose_name='物品描述', max_length=512, blank=True)


class ItemCategory(models.Model):
    """ 物品种类"""
    category_name = models.CharField(verbose_name="种类名称", max_length=32)

    def __str__(self):
        return self.category_name


class OrderInfo(models.Model):
    # item_id in database
    item = models.ForeignKey(verbose_name="物品id", to="ItemInfo", to_field="id", on_delete=models.CASCADE)

    item_name = models.CharField(verbose_name="物品名称", max_length=32)

    buyer = models.ForeignKey(verbose_name="买方id", to="UserInfo", to_field="id", on_delete=models.CASCADE)

    amount = models.DecimalField(verbose_name='交易价格', max_digits=10, decimal_places=2)

    order_time = models.DateField(verbose_name='支付时间', auto_now_add=True)

    order_status_choices = (
        (1, "未完成"),
        (2, "已完成"),
        (3, "已取消"),
    )

    order_status = models.SmallIntegerField(verbose_name="订单状态", choices=order_status_choices)

    order_complaint_choices = (
        (1, "未发起投诉"),
        (2, "已投诉，未回复"),
        (3, "已投诉，且回复"),
    )

    order_complaint_status = models.SmallIntegerField(verbose_name="订单投诉状态", choices=order_complaint_choices,
                                                      default=1)


class FavoriteInfo(models.Model):
    favorite_id = models.AutoField(primary_key=True)

    user = models.ForeignKey(verbose_name="用户id", to="UserInfo", to_field="id", on_delete=models.CASCADE)

    item = models.ForeignKey(verbose_name="物品id", to="ItemInfo", to_field="id", on_delete=models.CASCADE)

    favorite_time = models.DateField(verbose_name='收藏时间', auto_now_add=True)


class ShoppingCartInfo(models.Model):
    shoppingcart_id = models.AutoField(primary_key=True)

    user = models.ForeignKey(verbose_name="用户id", to="UserInfo", to_field="id", on_delete=models.CASCADE)

    item = models.ForeignKey(verbose_name="物品id", to="ItemInfo", to_field="id", on_delete=models.CASCADE)

    add_time = models.DateField(verbose_name='加购时间', auto_now_add=True)


class ComplaintInfo(models.Model):
    user = models.ForeignKey(verbose_name="用户id", to="UserInfo", to_field="id", on_delete=models.CASCADE)

    order = models.OneToOneField(verbose_name="订单id", to="OrderInfo", to_field="id",
                                 on_delete=models.CASCADE, primary_key=True)

    category_choices = (
        (1, "对卖家"),
        (2, "对物品"),
    )

    complaint_category = models.SmallIntegerField(verbose_name="投诉类别", choices=category_choices)

    complaint_time = models.DateField(verbose_name='投诉时间', auto_now_add=True)

    complaint_reason = models.TextField(verbose_name='投诉理由', max_length=512)

    complaint_choices = (
        (1, "未回复"),
        (2, "已回复"),
    )

    complaint_status = models.SmallIntegerField(verbose_name="投诉回复状态", choices=complaint_choices,
                                                default=1)


class HandlingOpinionInfo(models.Model):
    order = models.OneToOneField(verbose_name="订单id", to="OrderInfo", to_field="id",
                                 on_delete=models.CASCADE, primary_key=True)

    manager = models.ForeignKey(verbose_name="管理员", to="UserInfo", to_field="id", on_delete=models.CASCADE)

    opinion = models.TextField(verbose_name='处理意见', max_length=512)

    handling_time = models.DateField(verbose_name='处理时间', auto_now_add=True)

SecondHand/templates/admin_account_list.html
{% extends 'layout_admin.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px" class="clearfix">

            <div style="float: right;width: 300px;">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="请输入用户id"
                               value="{{ search_data }}">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                      </span>
                    </div>
                </form>
            </div>

        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                账号列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>用户ID</th>
                    <th>用户名</th>
                    <th>创建时间</th>
                    <th>用户状态</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    {% if obj.statustype == 2 %}
                        <tr userid="{{ obj.id }}">
                            <th>{{ obj.id }}</th>
                            <td>{{ obj.username }}</td>
                            <td>{{ obj.create_time }}</td>
                            <td>{{ obj.get_statustype_display }}</td>
                            <td>
                                <input userid="{{ obj.id }}" type="button" class="btn btn-info btn-xs btn-freeze"
                                       value="冻结">
                            </td>
                        </tr>
                    {% elif obj.statustype == 3 %}
                        <tr userid="{{ obj.id }}">
                            <th>{{ obj.id }}</th>
                            <td>{{ obj.username }}</td>
                            <td>{{ obj.create_time }}</td>
                            <td>{{ obj.get_statustype_display }}</td>
                            <td>
                                <input userid="{{ obj.id }}" class="btn btn-danger btn-xs btn-recover" type="button"
                                       value="恢复">
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}

                </tbody>
            </table>
        </div>

        <ul class="pagination">
            {{ page_string }}
        </ul>
    </div>

    <!-- 冻结（对话框） -->
    <div class="modal fade" id="freezeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">

            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <h4>是否确定冻结？</h4>
                <p style="margin: 10px 0;"> 冻结后，该账户将无法登录。</p>
                <p style="text-align: right;">
                    <button id="btnConfirmFreeze" type="button" class="btn btn-danger">确 定</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                </p>
            </div>

        </div>
    </div>


{% endblock %}

{% block js %}
    <script type="text/javascript">
        var FREEZE_ID;
        var RECOVER_ID;

        $(function () {
            bindBtnFreezeEvent();
            bindBtnConfirmFreezeEvent();
            bindBtnRecoverEvent();
        })

        function bindBtnFreezeEvent() {
            $(".btn-freeze").click(function () {
                // alert("点击了删除");
                // 显示删除对话框
                $("#freezeModal").modal('show');

                // 获取当前行的ID并赋值给全部变量。
                FREEZE_ID = $(this).attr("userid");
            });
        }

        function bindBtnConfirmFreezeEvent() {
            $("#btnConfirmFreeze").click(function () {
                $.ajax({
                    url: "/admin/account/freeze/",
                    type: "GET",
                    data: {
                        userid: FREEZE_ID
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.reload();
                        } else {
                            // 冻结失败
                            alert(res.error);
                        }
                    }
                })
            });
        }


        function bindBtnRecoverEvent() {
            $(".btn-recover").click(function () {

                var userid = $(this).attr("userid");
                RECOVER_ID = userid;

                $.ajax({
                    url: "/admin/account/recover/",
                    type: "GET",
                    data: {
                        userid: RECOVER_ID
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.reload();
                        } else {
                            // 恢复失败
                            alert(res.error);
                        }
                    }
                })
            });
        }

    </script>
{% endblock %}

SecondHand/templates/admin_complaint_list.html
{% extends 'layout_admin.html' %}

{#{% block css %}#}
{#<style>#}
{#    .truncate-cell {#}
{#        width: 100px; /* 设置单元格宽度 */#}
{#        white-space: nowrap; /* 防止文本换行 */#}
{#        overflow: hidden; /* 隐藏超出部分的文本 */#}
{#        text-overflow: ellipsis; /* 显示省略号 */#}
{#    }#}
{#</style>#}
{#{% endblock %}#}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px" class="clearfix">

            <div style="float: right;width: 300px;">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="输入订单id"
                               value="{{ search_data }}">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                      </span>
                    </div>
                </form>
            </div>

        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                投诉列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>投诉订单ID</th>
                    <th>投诉方</th>
                    <th>投诉类别</th>
                    <th>投诉理由</th>
                    <th>投诉时间</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    {% if obj.complaint_status == 1 %}
                        <tr orderid="{{ obj.order_id }}">
                            <th>{{ obj.order_id }}</th>
                            <td>{{ obj.user }}</td>
                            <td>{{ obj.get_complaint_category_display }}</td>
                            <td class="truncate-cell">{{ obj.complaint_reason }}</td>
                            <td>{{ obj.complaint_time }}</td>
                            <td>
                                <input orderid="{{ obj.order_id }}" type="button"
                                       class="btn btn-primary btn-xs btn-reply"
                                       value="回复">
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}

                </tbody>
            </table>
        </div>

        <ul class="pagination">
            {{ page_string }}
        </ul>
    </div>

    <!-- 新建 物品（对话框） -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">查看</h4>
                </div>
                <div class="modal-body">

                    <form id="formAdd">
                        <input id="order_id_input" hidden name="order_id">
                        <div class="clearfix">
                            {% for field in form %}
                                <div class="col-xs-12">
                                    <div class="form-group" style="position: relative;margin-bottom: 20px;">
                                        <label readonly="">{{ field.label }}</label>
                                        {{ field }}
                                        <span class="error-msg" style="color: red;position: absolute;"></span>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="col-xs-12">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">意见回复</label>
                                    <textarea class="form-control" name="reply" rows="4"></textarea>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    <button id="btnReplyConfirm" type="button" class="btn btn-primary">回 复</button>
                </div>

            </div>
        </div>
    </div>



{% endblock %}

{% block js %}
    <script type="text/javascript">

        var REPLY_ID;

        $(function () {
            bindBtnReplyEvent();
            truncateEvent();
            bindBtnConfirmEvent();

        })

        function truncateEvent() {
            $(".truncate-cell").each(function () {
                var maxLength = 20;
                var text = $(this).text();
                if (text.length > maxLength) {
                    $(this).text(text.substring(0, maxLength) + "...");
                }
            });
        }

        function bindBtnReplyEvent() {
            $(".btn-reply").click(function () {
                // 清空对话框中的数据
                $("#formAdd")[0].reset();
                REPLY_ID = $(this).attr("orderid");

                $("#order_id_input").val(REPLY_ID)


                // 发送Ajax去后端获取当前行的相关数据  /order/detail/?itemid=123
                $.ajax({
                    url: "/admin/complaint/reply/",
                    type: "get",
                    data: {
                        order_id: REPLY_ID
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            // 将数据赋值到对话框中的标签中。
                            $.each(res.data, function (name, value) {
                                $("#id_" + name).val(value);
                            })

                            // 点击编辑，显示对话框
                            $('#myModal').modal('show');
                        } else {
                            alert(res.error);
                        }
                    }
                });
            });
        }

        function bindBtnConfirmEvent() {
            $("#btnReplyConfirm").click(function () {

                var formData = $("#formAdd").serialize();

                $.ajax({
                    url: "/admin/complaint/reply/",
                    type: "post",
                    data: formData,
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {

                            // 关闭对话框
                            $('#myModal').modal('hide');

                            // 延时0.2秒后跳转到重新加载
                            setTimeout(function () {
                                location.reload();
                            }, 200);

                        } else {
                            // 把错误信息显示在对话框中。
                            $.each(res.error, function (name, errorList) {
                                $("#id_" + name).next().text(errorList[0]);
                            })
                        }
                    }
                });
            });

        }

    </script>
{% endblock %}

SecondHand/templates/favorite_list.html
{% extends 'layout_user.html' %}

{% block css %}
    <style>
        .item-description {
            width: 250px;
            color: #888888;
        }

        p {
            margin: 0 0 5px;
        }

        /*去除a标签下划线*/
        a {
            text-decoration: none;
        }

        /*去除未被访问的a标签的下划线*/
        a:link {
            text-decoration: none;
        }

        /*去除已经被访问过的a标签的下划线*/
        a:visited {
            text-decoration: none;
        }

        /*去除鼠标悬停时的a标签的下划线*/
        a:hover {
            text-decoration: none;
        }

        /*去除正在点击的a标签的下划线（鼠标按下，尚未松开）*/
        a:active {
            text-decoration: none;
        }

        /*去除获得焦点的a标签的下划线（被鼠标点击过）*/
        a:focus {
            text-decoration: none;
        }


        .hover-effect {
            border: 1px solid rgb(229, 229, 229);
            transition: background-color 0.3s, border-color 0.3s;
        }

        .hover-effect:hover {
            border-color: #cccccc;
            box-shadow: 0 5px 10px rgba(0, 0, 0, .1);
            -webkit-transform: translate3d(0, -2px, 0);
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">

        <div class="panel panel-default">

            <div class="panel-heading">
                <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                收藏列表
            </div>

            <div class="row" style="padding: 10px 10px 10px 10px">
                {% for item in favorite_list %}
                    <div class=" col-xs-2 " style="margin-top: 20px">
                        <div class="item_show text-center hover-effect" style="height: 250px">
                            <div style="width: 100px; margin-top: 5px; margin-bottom: 5px" class="center-block">
                                <a href="/item/detail/?itemid={{ item.item_id }}">
                                    <img src="/media/{{ item.item_img }}" class="img-responsive"
                                         alt="{{ item.item_name }}">
                                </a>
                            </div>
                            <a href="/item/detail/?itemid={{ item.item_id }}">{{ item.item_name }}</a>
                            <p>{{ item.price }}￥</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

SecondHand/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>香遇 PerfumeEncore</title>
    <link rel="icon" href="{% static 'img/logofont-removebg.png' %}" type="image/png">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
</head>
<body>

<div>
    <div class="jumbotron row " style="margin-top: 90px;">
        <div class="container text-center col-md-7" style="margin-top: 40px;">
            <h1>欢迎来到香遇</h1>
            <h2>PerfumeEncore</h2>
            <p>一个没人用的香氛转让网站</p>
            <p><a class="btn btn-primary btn-lg" href="/register/" role="button">点击注册</a></p>
            <p><a class="btn btn-primary btn-lg" href="/login/" role="button">点击登录</a></p>
        </div>

        <div class="col-md-5 ">
            <div style="width: 80%;" >
                <img class="img-responsive" src="{% static 'img/logo-removebg.png' %}" alt="logo">
            </div>
        </div>
    </div>
</div>


<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
</body>
</html>

SecondHand/templates/item_detail.html
{% extends 'layout_user.html' %}
{% load static %}
{% block css %}

    <style>
        .item-description {
            width: 250px;
            color: #888888;
        }

        p {
            margin: 0 0 10px;
        }

        .detail-title {
            padding: 10px 0 0;
            margin: 20px 0;
            font-size: 22px;
            color: #6e7099;
        }

        .description-title {
            padding: 10px 0 0;
            margin: 20px 0;
            font-size: 18px;
            color: #6e7099;
        }

        .hover-effect {
            border: 1px solid rgb(229, 229, 229);
            transition: background-color 0.3s, border-color 0.3s;
        }

        .hover-effect:hover {
            border-color: #cccccc;
            box-shadow: 0 5px 10px rgba(0, 0, 0, .1);
            -webkit-transform: translate3d(0, -2px, 0);
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">

        <div class="row center-block" style="margin-top: 10px; width: 80%">
            <div class="col-md-9">
                <h1 class="detail-title ">{{ item_object.item_name }}</h1>
                <div class="row">
                    <div class="col-md-6 ">
                        <div class="center-block" style="width: 60%;">
                            <img src="/media/{{ item_object.item_img }}" class="img-responsive"
                                 alt="{{ item_object.item_name }}">
                        </div>
                    </div>
                    <div class="col-md-6 " style="margin-top: 30px; padding-left: 40px;">
                        <p id="item-id" hidden>{{ item_object.id }}</p>
                        <p id="item-price" hidden>{{ item_object.price }}</p>
                        <p id="item-name" hidden>{{ item_object.item_name }}</p>
                        <p>物品种类：{{ item_object.item_category }}</p>
                        <p>卖家：{{ item_object.seller }}</p>
                        <p>价格：{{ item_object.price }}￥</p>
                        <p>购买时间：{{ item_object.purchase_time }}</p>
                        <p>新旧程度：{{ item_object.get_item_condition_display }}</p>
                        <p>交易位置：{{ item_object.location }}</p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 panel panel-default " style="margin-top: 50px;">
                <div class="panel-body center-block">
                    <p class="btn btn-primary" id="btnAddOrder">
                        <span class="glyphicon glyphicon-usd" aria-hidden="true"></span>
                        立即下单
                    </p>
                    <p></p>
                    <a href="/item/shoppingcart/add/?itemid={{ item_object.id }}" class="btn btn-warning">
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
                        加入购物车
                    </a>
                    <p></p>
                    <a href="/item/favorite/add/?itemid={{ item_object.id }}" class="btn btn-info">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                        加入收藏夹
                    </a>
                </div>
            </div>

        </div>

        <div class="center-block" style="width: 80%; margin-top: 30px; padding-left: 15px;">
            <h1 class="description-title ">物品描述</h1>
            <p>{{ item_object.item_description }}</p>

        </div>

    </div>


    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">订单-模拟支付</h4>
                </div>
                <div class="modal-body">
                    <img class="img-responsive center-block" alt="付款码" src="{% static 'img/打钱.png' %}"
                         style="width: 60%">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    <button id="btnSave" type="button" class="btn btn-primary">已支付</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
        })

        function bindBtnAddEvent() {
            $("#btnAddOrder").click(function () {

                // 点击新建按钮，显示对话框。
                $('#myModal').modal('show');
            });
        }

        function bindBtnSaveEvent() {
            $("#btnSave").click(function () {
                var ITEM_ID = document.getElementById("item-id").textContent;
                var AMOUNT = document.getElementById("item-price").textContent;
                var ITEM_NAME = document.getElementById("item-name").textContent;

                $.ajax({
                    url: "/order/add/",
                    type: "GET",
                    data: {
                        item_id: ITEM_ID,
                        item_name : ITEM_NAME,
                        amount: AMOUNT,
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {

                            // 关闭对话框
                            $('#myModal').modal('hide');

                            //跳转到/order/list/
                            window.location.href = '/order/list/';

                        } else {
                            alert("创建订单失败");
                        }
                    }
                })

            });
        }

    </script>
{% endblock %}

SecondHand/templates/order_item.html
{% extends 'layout_user.html' %}
{% load static %}
{% block css %}

    <style>
        .item-description {
            width: 250px;
            color: #888888;
        }

        p {
            margin: 0 0 10px;
        }

        .detail-title {
            padding: 10px 0 0;
            margin: 20px 0;
            font-size: 22px;
            color: #6e7099;
        }

        .description-title {
            padding: 10px 0 0;
            margin: 20px 0;
            font-size: 18px;
            color: #6e7099;
        }

    </style>
{% endblock %}

{% block content %}
    <div class="container">

        <div class="row center-block" style="margin-top: 10px; width: 80%">
            <div class="col-md-12">
                <h1 class="detail-title ">{{ item_object.item_name }}</h1>
                <div class="row">
                    <div class="col-md-6 ">
                        <div class="center-block" style="width: 60%;">
                            <img src="/media/{{ item_object.item_img }}" class="img-responsive"
                                 alt="{{ item_object.item_name }}">
                        </div>
                    </div>
                    <div class="col-md-6 " style="margin-top: 30px; padding-left: 40px;">
                        <p>物品种类：{{ item_object.item_category }}</p>
                        <p>卖家：{{ item_object.seller }}</p>
                        <p>价格：{{ item_object.price }}￥</p>
                        <p>购买时间：{{ item_object.purchase_time }}</p>
                        <p>新旧程度：{{ item_object.get_item_condition_display }}</p>
                        <p>交易位置：{{ item_object.location }}</p>
                    </div>
                </div>
            </div>

        </div>

        <div class="center-block" style="width: 80%; margin-top: 30px; padding-left: 15px;">
            <h1 class="description-title ">物品描述</h1>
            <p>{{ item_object.item_description }}</p>

        </div>

    </div>


{% endblock %}

{% block js %}
    <script type="text/javascript">
        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
        })

        function bindBtnAddEvent() {
            $("#btnAddOrder").click(function () {

                // 点击新建按钮，显示对话框。
                $('#myModal').modal('show');
            });
        }

        function bindBtnSaveEvent() {
            $("#btnSave").click(function () {
                var ITEM_ID = document.getElementById("item-id").textContent;
                var AMOUNT = document.getElementById("item-price").textContent;
                var ITEM_NAME = document.getElementById("item-name").textContent;

                $.ajax({
                    url: "/order/add/",
                    type: "GET",
                    data: {
                        item_id: ITEM_ID,
                        item_name : ITEM_NAME,
                        amount: AMOUNT,
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {

                            // 关闭对话框
                            $('#myModal').modal('hide');

                            //跳转到/order/list/
                            window.location.href = '/order/list/';

                        } else {
                            alert("创建订单失败");
                        }
                    }
                })

            });
        }

    </script>
{% endblock %}